### ISSUE TITLE
go generate panics when package imports a package using generics

### ISSUE THREAD

**Issue by jj-style** [moznion/gonstructor#25]
# Reproducible example

The following example attempts to use `gonstructor` with the example in the README and also uses `samber/lo` which has some generics.  

```go

package main

import (
	"fmt"
	"io"

	"github.com/samber/lo"
)

//go:generate go run github.com/moznion/gonstructor/cmd/gonstructor@latest --type=Structure --constructorTypes=allArgs
type Structure struct {
	foo string
	bar io.Reader
	Buz chan interface{}
}

func main() {
	numbers := []int{1, 2, 3, 4, 5}
	even := lo.Filter[int](numbers, func(item int, _ int) bool { return item%2 == 0 })
	fmt.Println(even)
}
```

The program runs, but `go generate ./...` gives
<details>
<summary>panic trace</summary>
```
❯ go generate ./...

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5923ef]

goroutine 49 [running]:
go/types.(*Checker).handleBailout(0xc0000d0600, 0xc0000e3c60)
	/usr/lib/go/src/go/types/check.go:367 +0x88
panic({0x6461a0?, 0x83b580?})
	/usr/lib/go/src/runtime/panic.go:770 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0x6e2f58, 0x83e4c0})
	/usr/lib/go/src/go/types/sizes.go:228 +0x30f
go/types.(*Config).sizeof(...)
	/usr/lib/go/src/go/types/sizes.go:333
go/types.representableConst.func1({0x6e2f58?, 0x83e4c0?})
	/usr/lib/go/src/go/types/const.go:76 +0x9e
go/types.representableConst({0x6e4040, 0x833f68}, 0xc0000d0600, 0x83e4c0, 0xc0000e1960)
	/usr/lib/go/src/go/types/const.go:92 +0x192
go/types.(*Checker).representation(0xc0000d0600, 0xc00015e640, 0x83e4c0)
	/usr/lib/go/src/go/types/const.go:256 +0x65
go/types.(*Checker).implicitTypeAndValue(0xc0000d0600, 0xc00015e640, {0x6e2f58, 0x83e4c0})
	/usr/lib/go/src/go/types/expr.go:375 +0x2d7
go/types.(*Checker).assignment(0xc0000d0600, 0xc00015e640, {0x6e2f58, 0x83e4c0}, {0x6889ac, 0x16})
	/usr/lib/go/src/go/types/assignments.go:52 +0x2e5
go/types.(*Checker).indexedElts(0xc0000d0600, {0xc0000a7880, 0x5, 0x7968979fa548?}, {0x6e2f58, 0x83e4c0}, 0xffffffffffffffff)
	/usr/lib/go/src/go/types/index.go:454 +0x15b
go/types.(*Checker).exprInternal(0xc0000d0600, 0x0, 0xc00015e5c0, {0x6e35a0, 0xc00015e1c0}, {0x0, 0x0})
	/usr/lib/go/src/go/types/expr.go:1247 +0x10dd
go/types.(*Checker).rawExpr(0xc0000d0600, 0x0, 0xc00015e5c0, {0x6e35a0?, 0xc00015e1c0?}, {0x0?, 0x0?}, 0x0)
	/usr/lib/go/src/go/types/expr.go:979 +0x19e
go/types.(*Checker).expr(0xc0000d0600, 0x0?, 0xc00015e5c0, {0x6e35a0?, 0xc00015e1c0?})
	/usr/lib/go/src/go/types/expr.go:1513 +0x30
go/types.(*Checker).initVars(0xc0000d0600, {0xc000190910, 0x1, 0x0?}, {0xc0002a7f20, 0xc00060aad8?, 0x461665?}, {0x0, 0x0})
	/usr/lib/go/src/go/types/assignments.go:381 +0x60b
go/types.(*Checker).shortVarDecl(0xc0000d0600, {0x6e1de0, 0xc00001a840}, {0xc0002a7f00, 0x1, 0xc00060adc8?}, {0xc0002a7f20, 0x1, 0x1})
	/usr/lib/go/src/go/types/assignments.go:556 +0x8f0
go/types.(*Checker).stmt(0xc0000d0600, 0x0, {0x6e3960, 0xc00015e200})
	/usr/lib/go/src/go/types/stmt.go:473 +0x15ff
go/types.(*Checker).stmtList(0xc0000d0600, 0x0, {0xc00015e3c0?, 0x2?, 0x3?})
	/usr/lib/go/src/go/types/stmt.go:121 +0x85
go/types.(*Checker).funcBody(0xc0000d0600, 0x6e3020?, {0xc000117950?, 0xc00039bf50?}, 0xc00015e540, 0xc000132600, {0x0?, 0x0?})
	/usr/lib/go/src/go/types/stmt.go:41 +0x331
go/types.(*Checker).funcDecl.func1()
	/usr/lib/go/src/go/types/decl.go:852 +0x3a
go/types.(*Checker).processDelayed(0xc0000d0600, 0x0)
	/usr/lib/go/src/go/types/check.go:467 +0x162
go/types.(*Checker).checkFiles(0xc0000d0600, {0xc000190840, 0x1, 0x1})
	/usr/lib/go/src/go/types/check.go:411 +0x1cc
go/types.(*Checker).Files(...)
	/usr/lib/go/src/go/types/check.go:372
golang.org/x/tools/go/packages.(*loader).loadPackage(0xc0000da000, 0xc0001f5de0)
	/home/jj/go/pkg/mod/golang.org/x/tools@v0.1.12/go/packages/packages.go:1001 +0x76f
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1()
	/home/jj/go/pkg/mod/golang.org/x/tools@v0.1.12/go/packages/packages.go:838 +0x1a9
sync.(*Once).doSlow(0xc0002eaf98?, 0x405f17?)
	/usr/lib/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	/usr/lib/go/src/sync/once.go:65
golang.org/x/tools/go/packages.(*loader).loadRecursive(0x5edcde?, 0xc0002eafd0?)
	/home/jj/go/pkg/mod/golang.org/x/tools@v0.1.12/go/packages/packages.go:826 +0x4a
golang.org/x/tools/go/packages.(*loader).refine.func2(0x0?)
	/home/jj/go/pkg/mod/golang.org/x/tools@v0.1.12/go/packages/packages.go:761 +0x26
created by golang.org/x/tools/go/packages.(*loader).refine in goroutine 1
	/home/jj/go/pkg/mod/golang.org/x/tools@v0.1.12/go/packages/packages.go:760 +0xc9a
exit status 2
main.go:10: running "go": exit status 1
```

</details>

**Comment by jj-style** [comment]
I think this is related https://github.com/golang/go/issues/51629
